question_data = [{"response_code": 0, "results": [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
                                      "question": "On which day did the World Wide Web go online?",
                                      "correct_answer": "December 20, 1990",
                                      "incorrect_answers": ["December 17, 1996", "November 12, 1990",
                                                            "November 24, 1995"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In the programming language &quot;Python&quot;, which of these statements would display the string &quot;Hello World&quot; correctly?",
     "correct_answer": "print(&quot;Hello World&quot;)",
     "incorrect_answers": ["console.log(&quot;Hello World&quot;)", "echo &quot;Hello World&quot;",
                           "printf(&quot;Hello World&quot;)"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In CSS, which of these values CANNOT be used with the &quot;position&quot; property?",
     "correct_answer": "center", "incorrect_answers": ["static", "absolute", "relative"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In computing terms, typically what does CLI stand for?", "correct_answer": "Command Line Interface",
     "incorrect_answers": ["Common Language Input", "Control Line Interface", "Common Language Interface"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What does &quot;LCD&quot; stand for?", "correct_answer": "Liquid Crystal Display",
     "incorrect_answers": ["Language Control Design", "Last Common Difference", "Long Continuous Design"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Released in 2001, the first edition of Apple&#039;s Mac OS X operating system (version 10.0) was given what animal code name?",
     "correct_answer": "Cheetah", "incorrect_answers": ["Puma", "Tiger", "Leopard"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In computing, what does LAN stand for?", "correct_answer": "Local Area Network",
     "incorrect_answers": ["Long Antenna Node", "Light Access Node", "Land Address Navigation"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "What type of sound chip does the Super Nintendo Entertainment System (SNES) have?",
     "correct_answer": "ADPCM Sampler",
     "incorrect_answers": ["FM Synthesizer", "Programmable Sound Generator (PSG)", "PCM Sampler"]}]}]
